//mod print;
//mod vars;
//mod types;
//mod strings;
//mod tuples;
//mod arrays;
// mod vectors;
//mod conditionals;
//mod loops;
//mod functions;
//mod pointer_ref;
//mod structs;
// mod enums;
//mod cli;
// mod ownerships;
//mod filters;
//mod traits;
// mod options;
// mod hashmaps;
// mod if_let;
// mod while_let;
// mod casting;
mod results;

fn main() {
    //println!("Hello, world!");
    //print::run();
    //vars::run();
    //types::run();
    //strings::run();
    //tuples::run();
    //arrays::run();
    // vectors::run();
    //conditionals::run();
    //loops::run();
    //functions::run();
    //pointer_ref::run();
    //structs::run();
    // enums::run();
    // cli::run();
    // ownerships::run();
    //filters::run();
    //traits::run();
    // options::run();
    // hashmaps::run();
    // if_let::run();
    // while_let::run();
    // casting::run();
    results::run();
}
